spring.application.name=SmartEmployeeManagementSystem

#Define logging levels as per packages
#logging.level.root=info

#Server configs
server.port=8090
server.servlet.context-path=/api
server.error.path= /error
#We can disable the default /error white labeled
#server.whitelabel.enabled=on

#Actuator Management configs
#This should be added if we want to stop our application by an actuators endpoint
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=health, shutdown, beans, mappings
#we can customize base path of actuator
management.endpoints.web.base-path=/management
management.server.port=8090

#h2 console
#spring.datasource.url=jdbc:h2:mem:akash
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=akash
#spring.datasource.password=akash
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

# Oracle DataSource Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/oraclepdb
spring.datasource.username=oracle
spring.datasource.password=Akash1592
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update